apiVersion: virtualrouter.tmax.hypercloud.com/v1
kind: FireWallRule
metadata:
  name: testfw
  namespace: virtualrouter
spec:
  rules:
  - match:
      srcIP: 10.10.10.0/24
      dstIP: 192.168.9.31/32
      protocol: all
    action:
      policy: ACCEPT
  - match:
      srcIP: 192.168.9.31/32
      dstIP: 10.10.10.0/24
      protocol: all
    action:
      policy: ACCEPT

    
    
