apiVersion: virtualrouter.tmax.hypercloud.com/v1
kind: LoadBalancerRule
metadata:
  name: testloadbalancer
  namespace: virtualrouter2
spec:
  rules:
  - loadBalancerIP: 192.168.8.156
    backends:
    - backendIP: 100.0.0.2
      weight: 40
      healthcheckIP: 100.0.0.2
      healthcheckPort: 80
      healthcheckMethod: icmp
    - backendIP: 100.0.0.3
      weight: 100
      healthcheckMethod: none
      healthcheckIP: 100.0.0.2
      healthcheckPort: 80