apiVersion: virtualrouter.tmax.hypercloud.com/v1
kind: NATRule
metadata:
  name: test2
  namespace: virtualrouter
spec:
  rules:
  - match:
      srcIP: 2.2.2.2/32
      dstIP: 3.3.3.3/32
      protocol: tcp
    action:
      dstIP: 0.0.0.0
    
    
