apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: natrules.virtualrouter.tmax.hypercloud.com
spec:
  group: virtualrouter.tmax.hypercloud.com
  names:
    kind: NATRule
    listKind: NATRuleList
    plural: natrules
    singular: natrule
  scope: Namespaced
  #scope: Cluster
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object representes'
          type: string
        metadata:
          type: object
        spec:
          type: object
          description: 'NATRuleSpec contains multiple natrules'
          properties:
            rules:
              type: array
              items:
                match:
                type: object
                properties:
                  srcIP:
                    type: string
                  dstIP:
                    type: string
                  srcPort:
                    type: integer
                  dstPort:
                    type: integer  
                  protocol:
                    type: string
                    pattern: ^(udp|tcp)
                action:
                type: object 
                properties:
                  srcIP:
                    type: string
                  dstIP:
                    type: string
                  srcPort:
                    type: integer
                  dstPort:
                    type: string  
